- name: Install Python and Flask
  hosts: backend
  become: true
  gather_facts: false

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: true

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure pip is installed for Python 3
      shell: python3 -m ensurepip --upgrade
      args:
        creates: /usr/bin/pip3

    - name: Install Flask using pip3
      pip:
        name: flask
        executable: pip3
