- name: Configure NGINX as a reverse proxy
  hosts: nginx
  become: true
  vars_files:
    - vars/backend-ip.yaml
  vars:   
    backend_port: 8080
 
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Configure reverse proxy in NGINX
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://{{ backend_ip }}:{{ backend_port }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: restarted
        enabled: true

