- name: Install simple Flask backend
  hosts: backend
  become: true
  gather_facts: no
  tasks:
    - name: Install Python and Flask
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: true

    - name: Install Flask
      pip:
        name: flask

    - name: Deploy test app
      copy:
        dest: /home/{{ ansible_user }}/app.py
        content: |
          from flask import Flask
          app = Flask(__name__)

          @app.route('/')
          def hello():
              return "Hello from backend VM!"

          if __name__ == "__main__":
              app.run(host="0.0.0.0", port=8080)

    - name: Start app
      shell: nohup python3 /home/{{ ansible_user }}/app.py &

