- name: Configure Nginx
  hosts: nginx
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Copy website files
      copy:
        src: ../src/index.html
        dest: /var/www/html/
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted
        enabled: true

